# Generated by Django 6.0.5 on 2026-05-13 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='event_type',
            field=models.CharField(choices=[('Rodajes', 'Rodajes'), ('Alojamiento', 'Alojamiento'), ('AIRBNB', 'AIRBNB'), ('Talleres y retiros', 'Talleres y retiros'), ('Celebraciones', 'Celebraciones'), ('Corporativo', 'Corporativo'), ('Catering & others', 'Catering & others')], default='Corporativo', max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('Rodajes', 'Rodajes'), ('Alojamiento', 'Alojamiento'), ('AIRBNB', 'AIRBNB'), ('Talleres y retiros', 'Talleres y retiros'), ('Celebraciones', 'Celebraciones'), ('Corporativo', 'Corporativo'), ('Catering & others', 'Catering & others')], default='Corporativo', max_length=50),
        ),
    ]
