# Generated by Django 6.0.5 on 2026-06-08 23:44

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_presupuesto_event_type_alter_event_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_name', models.CharField(max_length=255)),
                ('client_facing_name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Rodajes', 'Rodajes'), ('Alojamiento', 'Alojamiento'), ('AIRBNB', 'AIRBNB'), ('Talleres y retiros', 'Talleres y retiros'), ('Celebraciones', 'Celebraciones'), ('Corporativo', 'Corporativo'), ('Catering & others', 'Catering & others')], max_length=50)),
                ('internal_notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='presupuesto',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='presupuesto',
            name='status',
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('Deposit', 'Deposit'), ('Final', 'Final')], default='Deposit', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='invoices/'),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presupuesto', to='crm.event'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='presupuesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='crm.presupuesto'),
        ),
        migrations.CreateModel(
            name='PresupuestoVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Sent', 'Sent'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Archived', 'Archived')], default='Draft', max_length=50)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='presupuestos/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='crm.presupuesto')),
            ],
            options={
                'ordering': ['-version_number'],
                'unique_together': {('presupuesto', 'version_number')},
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='presupuesto_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='crm.presupuestoversion'),
        ),
        migrations.CreateModel(
            name='ServicePriceBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_units', models.PositiveIntegerField()),
                ('max_units', models.PositiveIntegerField(blank=True, null=True)),
                ('unit_label', models.CharField(max_length=50)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=8)),
                ('flat_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_bands', to='crm.servicecatalogitem')),
            ],
            options={
                'ordering': ['service', 'min_units'],
            },
        ),
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=8)),
                ('unit_label', models.CharField(max_length=50)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('show_on_client_pdf', models.BooleanField(default=True)),
                ('client_display_name', models.CharField(blank=True, max_length=255)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='crm.presupuestoversion')),
                ('catalog_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='line_items', to='crm.servicecatalogitem')),
                ('price_band_used', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='line_items', to='crm.servicepriceband')),
            ],
        ),
    ]
