# Generated by Django 6.0.5 on 2026-06-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_servicecatalogitem_remove_presupuesto_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
