# Generated by Django 6.0.5 on 2026-06-09 18:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_invoice_paid_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='issue_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
