# Generated by Django 6.0.5 on 2026-06-25 10:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_alter_invoice_issue_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuestoversion',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='presupuestoversion',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='presupuestoversion',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='presupuestoversion',
            name='viewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='presupuestoversion',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Sent', 'Sent'), ('Viewed', 'Viewed'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Archived', 'Archived')], default='Draft', max_length=50),
        ),
    ]
