# Generated by Django 6.0.5 on 2026-07-22 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_presupuestoversion_accepted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_date_tentative',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='is_date_tentative',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='event_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='event_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
