# Generated by Django 6.0.5 on 2026-07-22 14:09

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_event_is_date_tentative_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='requires_security_deposit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='security_deposit_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
